import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "./_sections/Header";
import "./globals.css";
import { ErrorWrapper } from "./error-wrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "Next.js Tutorial",
    template: "%s | Sample",
    // absolute: "",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header />
        <div id="content-section">
          <ErrorWrapper>{children}</ErrorWrapper>
        </div>
        <footer>Footer</footer>
      </body>
    </html>
  );
}
